---
title: "Metodos de clusterización para features de alto nivel de Spotify"
output:
  html_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)

```


```{r} 
#Chequea e instala paquetes

if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(readxl, ggplot2, RColorBrewer, ggbiplot, GGally,dendextend, corrplot, gridExtra, plot3D, dplyr, tidyr, devtools,
               arules, caret, mvnormtest, heplots, mvnormtest, e1071, cluster, pracma, factoextra, NbClust)

# carga manual de paquetes
 library(readxl) #lee xls como dataframe
 library(ggplot2) #paquete de graficos
 library(RColorBrewer) #complemento ggplot
 library(ggbiplot) #para graficar biplot
 library(GGally) #complemento ggplot
 library(dendextend) #complemento para graficar dendrograma
 library(corrplot) #para graficar matrices de correlacion
 library(gridExtra) #complemento ggplot
 library(plot3D) #graficos scatter 3D
 library(dplyr)  #herramienta de manejo de datos
 library(tidyr)  #herramienta de manejo de datos
 library(devtools) # herramientas estadísticas
 library(arules)  # herramientas estadísticas
 library(caret) #herramientas de regresion y clasificacion
 library(mvnormtest) #test normalidad multivariada 
 library(heplots)  # herramientas estadísticas
 library(e1071)  # herramientas estadísticas
 library(cluster) #paquete de clusters
 library(pracma)  # herramientas estadísticas
 library(factoextra) # herramientas estadísticas
 library(NbClust) # tests de cantidad de clusters optimos 
 library(ape)

```

```{r}
#######################################  clasificación no supervisada ################################################

######## Carga de datos ########### 
spotify_completo = read_xlsx('spotify.xlsx')
n=round(0.7* nrow(spotify_completo)) 
set.seed(36761117);
cuales= sample(1:nrow(spotify_completo), size=n,  replace=FALSE)
spotify = spotify_completo[cuales,]

```

```{r ##### pre-procesamiento ####}


#conversion genero a factors
spotify$genre = as.factor(spotify$genre)
#eliminacion de algunos outliers
spotify = filter(spotify, duration_ms < 900000, speechiness < 0.60)

# Escalado de los datos numericos
spotify_num = data.frame(scale(spotify[-c(1)]))


#Alternativa, escalado robusto
#spotify_num = data.frame(scale(spotify[-c(1)], center=apply(spotify[-c(1)],2, "median"),  scale=apply(spotify[-c(1)],2, "IQR")))


```

```{r # Scatter plots exploratorio } 


funcionscatter <- function(data,mapping,  ...){
  x <- GGally::eval_data_col(data, mapping$x)
  y <- GGally::eval_data_col(data, mapping$y)
  df <- data.frame(x = x, y = y)
  
  pp <- ggplot(df, aes(x=x, y=y, color = spotify$genre)) +
    ggplot2::geom_point(shape=16, show.legend = T, size= 1.5, alpha = 0.6) +
    guides(color = guide_legend(override.aes = list(size = 4))) +
    ggplot2::scale_alpha(range = c(0.05, 0.6)) +
    ggplot2::labs(colour = "Genre") +
    theme_minimal() +
    theme(legend.position = "bottom", legend.key.size = unit(5,"point"))  
  
  return(pp)
}


leyenda = grab_legend(funcionscatter(spotify, aes(popularity, tempo, color = genre)) )


#completo
ggpairs(spotify, columns = c(2:9),
        lower = list(continuous = funcionscatter),  axisLabels = "none", 
        legend = leyenda,
        upper = "blank")  +
        theme_minimal() + 
        theme(legend.position = "bottom")


#resumido
ggpairs(spotify, columns = c(2,3,4),
        lower = list(continuous = funcionscatter),  axisLabels = "none", 
        legend = leyenda,
        upper = "blank")  +
        theme_minimal() + 
        theme(legend.position = "bottom")


```
```{r ###### Componentes principales ####### }

datos.pc = prcomp(spotify_num,scale = T)
spotify_componentes = data.frame(datos.pc$x)

#biplot coloreado con generos musicales
ggbiplot(datos.pc, obs.scale=1 , alpha=0.5,  labels.size= 4, varname.adjust=1.5,
groups = as.factor(spotify$genre), ellipse = F, var.axes= T, circle = F, varname.abbrev= F ) +
  theme_minimal()



#biplot coloreado con genero y popularidad
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify$genre), alpha = 0.4, size = spotify$popularity/15 ) +
  labs(color = 'Generos') + 
  guides(color = guide_legend(override.aes = list(size = 4))) +
  scale_color_manual(values = colorRampPalette(brewer.pal(8, "Set1"))(13)) +
  theme_minimal() +
  theme(legend.position = 'bottom')


#biplot coloreado con variable numérica valence
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$valence, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="limegreen", high="red") +
  theme_minimal() +
  theme(legend.position = 'bottom')

#biplot coloreado con variable numérica liveness
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$liveness, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="yellow2", high="red") +
  theme_minimal() +
  theme(legend.position = 'bottom')

#biplot coloreado con variable numérica acousticness
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$acousticness, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="cyan", high="red") +
  theme_minimal() +
  theme(legend.position = 'bottom')


#biplot coloreado con variable numérica energy
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$energy, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="slateblue2", high="red") +
  theme_minimal() +
  theme(legend.position = 'bottom')


#biplot coloreado con variable numérica speechiness
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$speechiness, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="grey62", high="red") +
  theme_minimal() +
  theme(legend.position = 'bottom')



#biplot coloreado con variable numérica speechiness
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_num$danceability, size = spotify$popularity/15 ),alpha = 0.4) +
  scale_color_gradient(low="grey62", high="dodgerblue4") +
  theme_minimal() +
  theme(legend.position = 'bottom')

```

```{r}
####### EVALUACION NUMERO OPTIMO DE CLUSTERS ##### 

optimo <- NbClust(spotify_num, distance='euclidean', max.nc=9, method="kmeans")
table(optimo$Best.nc[1,])
barplot(table(optimo$Best.nc[1,]), xlab="Clusters", ylab="Criterios", 
        main="Numero de clusters por criterio")

# SSW
fviz_nbclust(spotify_num, kmeans, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")

# Silhouette 
fviz_nbclust(spotify_num, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")

# Gap 
set.seed(36761117)
fviz_nbclust(spotify_num, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")

```

```{r ########## KMEANS #######}
set.seed(3676117)
CL  = kmeans(spotify_num,4,nstart=25,iter.max = 100)
spotify_kmeans = spotify
spotify_kmeans$kmeans = as.factor(CL$cluster)


```

```{r PLOTS KMEANS}
# Visualizacion en biplot
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify_kmeans$kmeans), alpha = 0.4, size = spotify_kmeans$popularity/15 ) +
  labs(color = 'Clusters') + 
  guides(color = guide_legend(override.aes = list(size = 4))) +
  scale_color_manual(values =c("dodgerblue2", "deeppink2", "orangered2", "springgreen4")) +
  theme_minimal() +
  theme(legend.position = 'bottom')

#Visualización como clusplot
clusplot(spotify_num, spotify_kmeans$kmeans, color=TRUE, shade=TRUE, 
         labels=8)

#Visualización 3 componentes principales
scatter3D(x=datos.pc$x[,1], y=datos.pc$x[,2], z=datos.pc$x[,3], colvar=as.integer(spotify_kmeans$kmeans),  
         bty = "g", pch = 20, cex = 1,theta = 140, phi = 30,
          xlab = "pc1", ylab ="pc2", zlab = "pc3", labels = c("1", "2", "3", "4"))

# Que variables representa cada cluster (K-MEANS)
spotify_kmeans %>% 
  group_by(kmeans) %>% 
  summarise(Acustico = mean(acousticness),
            Volumen = mean(loudness),
            Danza = mean(danceability),
            Energia = mean(energy),
            Publico = mean(liveness),
            Palabras = mean(speechiness),
            Popularidad = mean(popularity),
            Tempo = mean(tempo),
            Positividad = mean(valence)) %>% 
        dplyr::select(kmeans, Acustico, Volumen, Danza, Energia, Publico, Palabras, Popularidad, Positividad, Tempo) %>%
        gather("Name","Value",-kmeans) %>% 
      ggplot(aes(y=Value,x = kmeans,col=Name,group = Name)) +
      geom_point()+
      geom_line()+
      facet_wrap(~Name,scales = "free_y")+
      scale_color_brewer(palette = "Paired")+
      theme_minimal()+
      theme(legend.position = "none") +
      labs(x="Cluster",col = "Variable",title = "Variables para cada cluster")
    
# cluster y generos    
ggplot(spotify_kmeans, aes(kmeans, genre, color=kmeans)) +
  geom_jitter(width = 0.2, height	= 0.1, alpha = 0.3, size = 2) +
  scale_color_manual(values =c("dodgerblue2", "deeppink2", "orangered2", "springgreen4")) +
    theme_minimal() +
  theme(legend.position = 'none')


```
```{r ######## CLUSTER JERARQUICO #########}

#Comparación de coeficientes cofenéticos
distancias = c("euclidean",  "manhattan", "minkowski")
metodos =  c("ward.D2", "single", "complete", "average", "median", "centroid")

for( i in 1:length(distancias)){
  matdist <- dist(x = spotify_num, method = distancias[i]) 
  for(j in 1:length(metodos)){
    hc = hclust(d = matdist, method= metodos[j])
    cofenetico = cor(x = matdist, cophenetic(hc))
    print(c(distancias[i],metodos[j],cofenetico))
  }
}

```

```{r}
mat_dist <- dist(x = spotify_num, method = "euclidean")    

# Dendrogramas (según el tipo de segmentación jerárquica aplicada)  
#hc_complete <- hclust(d = mat_dist, method = "complete")  
#hc_average  <- hclust(d = mat_dist, method = "average")
#hc_single   <- hclust(d = mat_dist, method = "single") 
hc_ward     <- hclust(d = mat_dist, method = "ward.D2")   # Finalmente decido método de Ward
```

```{r}
#Elección de 4 clusters
grupos = cutree(hc_ward,k=4)
spotify$clusters = as.factor(grupos)

# construccion de un dendograma, se prueba con diferentes k y algoritmos 
plot(hc_ward)
rect.hclust(hc_ward, k=4, border="red")

#Dendograma circular
spotify$genre_n = as.numeric(as.factor(spotify$genre))
plot(ape::as.phylo(hc_ward), type = "fan", tip.color = as.integer(spotify$clusters),
     label.offset = 1, cex = 0.7)
```

```{r PLOTS CLUSTERIZACION JERARQUICA}


ggplot(spotify, aes(clusters, genre, color=genre)) +
  geom_jitter(width = 0.2, height	= 0.1, alpha = 0.5, size = 2) +
  theme_minimal()

# Visualizacion en biplot
ggplot(spotify_componentes, aes(x= PC1, y=PC2)) +
  geom_point(aes(color=spotify$clusters), alpha = 0.4, size = spotify$popularity/15 ) +
  labs(color = 'Clusters') + 
  guides(color = guide_legend(override.aes = list(size = 4))) +
  scale_color_manual(values =c("orangered2", "deeppink2", "dodgerblue2", "springgreen4"), labels = c("A", "B", "C", "D")) +
  theme_minimal() +
  theme(legend.position = 'bottom')



# Que variables representa cada cluster  (WARD)
spotify %>% 
  group_by(clusters) %>% 
  summarise(Acustico = mean(acousticness),
            Volumen = mean(loudness),
            Danza = mean(danceability),
            Energia = mean(energy),
            Publico = mean(liveness),
            Palabras = mean(speechiness),
            Popularidad = mean(popularity),
            Tempo = mean(tempo),
            Positividad = mean(valence)) %>% 
  dplyr::select(clusters, Acustico, Volumen, Danza, Energia, Publico, Palabras, Popularidad, Positividad, Tempo) %>%
  gather("Name","Value",-clusters) %>% 
  ggplot(aes(y=Value,x = clusters,col=Name,group = Name)) +
  scale_x_discrete(labels = c("A", "B", "C", "D")) +
  geom_point()+
  geom_line()+
  facet_wrap(~Name,scales = "free_y")+
  scale_color_brewer(palette = "Paired")+
  theme_minimal()+
  theme(legend.position = "none") +
  labs(x="Cluster",col = "Variable")

# genero en cada cluster
ggplot(spotify, aes(clusters, genre, color=clusters)) +
  geom_jitter(width = 0.2, height	= 0.1, alpha = 0.3, size = 2) +
  scale_x_discrete(labels = c("A", "B", "C", "D")) +
  scale_color_manual(values =c("orangered2", "deeppink2", "dodgerblue2", "springgreen4")) +
  theme_minimal() +
  theme(legend.position = 'none')
```
```{r}

#### CLUSTERIZACION JERARQUICA SOBRE GENERO

spotify_var = spotify[-c(2,5,7)] %>% group_by(genre) %>% summarise_if(is.numeric, .funs = c('media' = mean, 'var' = var))
spotify_var[-1] = scale(spotify_var[-1])

mat_dist_generos <- dist(x = spotify_var[-1], method = "euclidean") 

hc_generos <- hclust(d = mat_dist_generos, method = "ward.D")
hc_generos$labels = spotify_var$genre


dend = as.dendrogram(hc_generos)
dend %>%    set("labels_cex", 1.2) %>% 
  set("labels_col", value = c("orangered2", "deeppink2", "dodgerblue2", "orange2", "springgreen4"), k=5)  %>% plot  
abline(h = 5, lty = 2) 
```

